FROM nginx:stable-alpine
LABEL org.opencontainers.image.source="https://github.com/ankitamandlik5-web/main"
LABEL org.opencontainers.image.description="Lab 1 static page by Ankita Mandlik"
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
